### ISSUE TITLE
PHP 7.2 Support

### ISSUE THREAD

**Issue by mschwager** [ChadSikorra/ps-install-php#1]
Hey!

First off, thanks for this project! It's awesome, and makes running PHP tests on AppVeyor dead simple. PHP 7.2 was just released, and it looks like the install script needs a few tweaks to make it work. Here's the specific build I'm looking at:

https://ci.appveyor.com/project/mschwager/duo-php/build/1.0.0.4/job/almlxfyas9dm5hp9

It looks like the `$VC` variable needs to be updated to include VC15, as that's what PHP 7.2 is requiring. I tried to find the executable myself, but couldn't find anything on download.microsoft.com. Maybe I'm just looking in the wrong place.

Thoughts?

**Comment by mschwager** [comment]
Actually, looks like they're at:

* https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe
* https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe

**Comment by ChadSikorra** [comment]
Thanks for reporting this! Haven't gotten around to bumping the version in any of my libraries yet. I'll take a look to get this sorted out. Thanks for finding the download links.

**Comment by ChadSikorra** [comment]
Should be working now. I added the new links for VC15 (and removed some useless semicolons at the same time...) here: https://github.com/ChadSikorra/ps-install-php/commit/b57c04964d2c709c4bacbfd90720f6673b427124. I'll be trying it out after work.

**Comment by mschwager** [comment]
It works! https://ci.appveyor.com/project/mschwager/duo-php/build/1.0.0.5

Thanks again!
